name: country_code_picker
description: A flutter package for showing a country code selector. 
version: 0.2.2
author: Salvatore-Giordano <svtgiordano@gmail.com>
homepage: https://github.com/Salvatore-Giordano/CountryCodePicker

environment:
  sdk: ">=1.2.0  <=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_icons: "^0.0.2"
