name: Dart CI

on:
  push:
    tags: 
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - name: Publish Dart/Flutter package
      uses: sakebook/actions-flutter-pub-publisher@v1.2.1
      with:
        credential: ${{ secrets.CREDENTIALS }}
        flutter_package: true
        skip_test: true
